In [1]:
import os, warnings
import matplotlib.pyplot as plt
from matplotlib import gridspec
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn import preprocessing
import PIL

In [5]:
img_dims=(300, 300)
batch_size=126
Data_dir='/home/louay/Desktop/ML/RPC/'

train_Data_gen = tf.keras.preprocessing.image.ImageDataGenerator(
      rescale = 1./255,
      rotation_range=40,
      width_shift_range=0.2,
      height_shift_range=0.2,
      shear_range=0.2,
      zoom_range=0.2,
      horizontal_flip=True,
      fill_mode='nearest'
      validation_split=0.5)

train_generator = train_Data_gen.flow_from_directory(
	Data_dir+'rps',
	target_size=(150,150),
	class_mode='categorical',
  batch_size=batch_size
)

val_Data_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale = 1./255)

validation_generator = val_Data_gen.flow_from_directory(
	Data_dir+'rps-test-set',
	target_size=(150,150),
	class_mode='categorical',
  batch_size=batch_size
)


Found 2520 images belonging to 3 classes.
Found 372 images belonging to 3 classes.


In [6]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(150, 150, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
 
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])
model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [7]:
history = model.fit(train_generator, epochs=25, steps_per_epoch=20, validation_data = validation_generator, verbose = 1, validation_steps=3)

Epoch 1/25
20/20 [==============================] - 27s 975ms/step - loss: 1.4726 - accuracy: 0.3431 - val_loss: 1.0960 - val_accuracy: 0.3333
Epoch 2/25
20/20 [==============================] - 20s 993ms/step - loss: 1.1106 - accuracy: 0.3708 - val_loss: 0.9326 - val_accuracy: 0.6747
Epoch 3/25
20/20 [==============================] - 20s 1s/step - loss: 1.1381 - accuracy: 0.4770 - val_loss: 0.7427 - val_accuracy: 0.6452
Epoch 4/25
20/20 [==============================] - 20s 999ms/step - loss: 0.9135 - accuracy: 0.5597 - val_loss: 0.6028 - val_accuracy: 0.9328
Epoch 5/25
20/20 [==============================] - 20s 973ms/step - loss: 0.8508 - accuracy: 0.6647 - val_loss: 0.3537 - val_accuracy: 0.9892
Epoch 6/25
20/20 [==============================] - 21s 1s/step - loss: 0.7915 - accuracy: 0.6793 - val_loss: 1.0450 - val_accuracy: 0.4946
Epoch 7/25
20/20 [==============================] - 20s 983ms/step - loss: 0.7646 - accuracy: 0.6721 - val_loss: 0.9614 - val_accuracy: 0.4543
Epoch

In [13]:
real_test=PIL.Image.open('/home/louay/Desktop/ML/dump/2/3.png').resize((150,150))
pred=model.predict(np.expand_dims(real_test, axis=0))
np.argmax(np.round(pred),axis=1)

array([2])

In [22]:
images=[PIL.Image.open('/home/louay/Desktop/Raspberry/dump/5/'+str(i)).resize((150,150)) for i in range(1000)]
preds=[model.predict(np.expand_dims(img, axis=0)) for img in images]
single_value_pred=[np.argmax(np.round(pred),axis=1) for pred in preds]

In [23]:
single_value_pred

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),